# filepath: docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: visitrack-app
    container_name: visitrack-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - visitrack
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: visitrack-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - visitrack
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: visitrack-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: visitrack
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - visitrack

volumes:
  dbdata:

networks:
  visitrack:
    driver: bridge